.PHONY: run
run:
	$(MAKE) partone
	$(MAKE) parttwo

.PHONY: partone
partone:
	python python/day_one.py data-daterr.jsonl 2 2020

.PHONY: parttwo
parttwo:
	python python/day_one.py data-daterr.jsonl 3 2020
