.PHONY: run
run:
	$(MAKE) partone
	$(MAKE) parttwo

.PHONY: partone
partone:
	python python/day_seventeen.py data-daterr.txt 6 3

.PHONY: parttwo
parttwo:
	python python/day_seventeen.py data-daterr.txt 6 4
