.PHONY: run
run:
	$(MAKE) partone
	$(MAKE) parttwo

.PHONY: partone
partone:
	python python/day_fifteen.py data-daterr.txt 2020

.PHONY: parttwo
parttwo:
	python python/day_fifteen.py data-daterr.txt 30000000
